trigger:
- none

pool:
  vmImage: Self Hosted

jobs:
- job: job1
  pool: Self Hosted
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'Write-Host "Hello World"'
      pwsh: true
- job: job2
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: '1..10 | Foreach-Object { Write-Host "Count $_ and wait 5 seconds"; Start-Sleep -Seconds 5}'
      pwsh: true
- job: job3
  dependsOn: [job1, job2]
  pool: Self Hosted
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: '1..10 | Foreach-Object { Write-Host "Count $_ and wait 5 seconds"; Start-Sleep -Seconds 5}'
      pwsh: true
