parameters:
- name: groupname
- name: pool
  default: none

jobs:
- job: job
  pool:
    ${{ if eq(parameters.pool, 'none') }}:
      vmImage: ubuntu-latest
    ${{ else }}:
      name: ${{ parameters.pool }}
  variables:
  - group: ${{ parameters.groupname }}
  steps:
  - task: PowerShell@2
    displayName: Count to $(countTo)
    inputs:
      targetType: 'inline'
      script: '1..$(countTo) | Foreach-Object { Write-Host "Count $_ and wait 5 seconds"; Start-Sleep -Seconds 5}'
      pwsh: true